package com.swp391.horseracing.enums;

public enum NotificationEventType {
    TOURNAMENT_PUBLISHED,
    REGISTRATION_APPROVED,
    REGISTRATION_REJECTED,
    REGISTRATION_WITHDRAWN,
    CONTRACT_INVITED,
    CONTRACT_ACCEPTED,
    CONTRACT_REJECTED,
    CONTRACT_APPROVED,
    CONTRACT_CANCELLED,
    SCHEDULE_PUBLISHED,
    RACE_RESCHEDULED,
    RACE_CANCELLED,
    RACE_STARTED,
    ENTRY_SCRATCHED,
    HORSE_INSPECTION_FAILED,
    JOCKEY_INSPECTION_FAILED,
    RACE_RESULT_PUBLISHED,
    PREDICTION_SCORED,
    PREDICTION_VOIDED,
    PREDICTED_ENTRY_SCRATCHED,
    PRIZE_RECEIVED,
    JOCKEY_PAYOUT_RELEASED
}
