package com.swp391.horseracing.enums;

public enum TransactionType {
    DEPOSIT,

    OWNER_REGISTRATION_FEE,

    JOCKEY_HIRING_FEE,
    JOCKEY_HIRING_ESCROW,
    JOCKEY_HIRING_ADVANCE_PAYOUT,
    JOCKEY_HIRING_ADVANCE_INCOME,
    JOCKEY_HIRING_FINAL_PAYOUT,
    JOCKEY_HIRING_FINAL_INCOME,

    CONTRACT_CREATION_FEE,

    PRIZE_OWNER_SHARE,
    PRIZE_JOCKEY_SHARE,

    REFUND
}
