# Development Profile Configuration
logging.level.root=info
logging.level.com.swp391.horseracing=debug

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.out-of-order=true
